name: Push-to-EC2-Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy Node.js app to EC2 (staging)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Deploy project files to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: ${{ secrets.EC2_PATH }}

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update system packages
            sudo apt-get update -y
            
            # Install Node.js (using NodeSource repository for latest version)
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs git
            
            # Remove any existing PM2 installation to avoid conflicts
            sudo npm uninstall -g pm2 || true
            
            # Install PM2 globally
            sudo npm install -g pm2@latest
            
            # Go to app directory
            cd ${{ secrets.EC2_PATH }}
            
            # Stop existing PM2 processes
            pm2 stop staging-app || true
            pm2 delete staging-app || true
            
            # Write .env from GitHub Secret
            echo "${{ secrets.ENV_FILE }}" > .env
            
            # Verify .env file was created correctly
            echo "=== .env file contents (first few lines, sensitive data hidden) ==="
            head -3 .env | sed 's/=.*/=***HIDDEN***/'
            
            # Install dependencies
            npm install 
            
            # Start app with PM2
            pm2 start src/index.js --name staging-app
            
            # Save PM2 configuration
            pm2 save
            
            # Setup PM2 to start on boot (only run once)
            pm2 startup systemd -u ${{ secrets.EC2_USER }} --hp /home/${{ secrets.EC2_USER }} || true