name: Push-to-EC2-Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy Node.js app to EC2 (staging)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy project files to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: ${{ secrets.EC2_PATH }}

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update package list
            sudo apt-get update -y
            
            # Install Node.js using NodeSource repository (more reliable)
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs nginx
            
            # Verify installations
            node --version
            npm --version
            nginx -v
            
            # Go to app directory and install dependencies
            cd ${{ secrets.EC2_PATH }}
            npm install
            
            # Stop existing services if running
            sudo systemctl stop nodeapp || true
            sudo systemctl stop nginx || true
            
            # Create systemd service file for Node app
            sudo tee /etc/systemd/system/nodeapp.service > /dev/null <<EOF
            [Unit]
            Description=Node.js App
            After=network.target
            
            [Service]
            Type=simple
            ExecStart=/usr/bin/node ${{ secrets.EC2_PATH }}/src/index.js
            Restart=always
            RestartSec=10
            User=${{ secrets.EC2_USER }}
            Group=${{ secrets.EC2_USER }}
            Environment=NODE_ENV=production
            Environment=PORT=8000
            WorkingDirectory=${{ secrets.EC2_PATH }}
            StandardOutput=journal
            StandardError=journal
            
            [Install]
            WantedBy=multi-user.target
            EOF
            
            # Reload systemd and start service
            sudo systemctl daemon-reload
            sudo systemctl enable nodeapp
            sudo systemctl start nodeapp
            
            # Wait for the service to start
            sleep 5
            
            # Check if service is running
            sudo systemctl status nodeapp --no-pager
            
            # Remove default nginx site
            sudo rm -f /etc/nginx/sites-enabled/default
            
            # Create nginx sites directories if they don't exist
            sudo mkdir -p /etc/nginx/sites-available
            sudo mkdir -p /etc/nginx/sites-enabled
            
            # Configure Nginx reverse proxy
            sudo tee /etc/nginx/sites-available/nodeapp > /dev/null <<EOF
            server {
                listen 80;
                server_name ${{ secrets.EC2_HOST }} _;
                
                # Security headers
                add_header X-Frame-Options "SAMEORIGIN" always;
                add_header X-XSS-Protection "1; mode=block" always;
                add_header X-Content-Type-Options "nosniff" always;
                
                location / {
                    proxy_pass http://localhost:8000;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade \$http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto \$scheme;
                    proxy_cache_bypass \$http_upgrade;
                    proxy_read_timeout 86400;
                }
                
                # Health check endpoint (optional)
                location /health {
                    access_log off;
                    return 200 "healthy\n";
                    add_header Content-Type text/plain;
                }
            }
            EOF
            
            # Enable site
            sudo ln -sf /etc/nginx/sites-available/nodeapp /etc/nginx/sites-enabled/
            
            # Test nginx configuration
            sudo nginx -t
            
            # Start and enable nginx
            sudo systemctl enable nginx
            sudo systemctl start nginx
            
            # Check nginx status
            sudo systemctl status nginx --no-pager
            
            # Show listening ports
            sudo netstat -tlnp | grep :80 || sudo ss -tlnp | grep :80
            
            echo "Deployment completed successfully!"
            echo "Your app should now be accessible at: http://${{ secrets.EC2_HOST }}/"