name: Push-to-EC2-Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy Node.js app to EC2 (staging)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy project files to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: ${{ secrets.EC2_PATH }}

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure Node & PM2
            sudo apt-get update -y
            sudo apt-get install -y nodejs npm git
            sudo npm install -g pm2

            # Go to app directory
            cd ${{ secrets.EC2_PATH }}

            # Install dependencies
            npm install --production

            # Restart app with PM2 (create if first time)
            pm2 restart src/index.js || pm2 start src/index.js

            # Ensure PM2 restarts on reboot
            pm2 save
            pm2 startup || true
